export default [
  { label: 'ANSI', width: 'label', group: true },

  { name: 'Esc', code: 'KC_ESC', keys: 'esc' },
  { width: 1000 },
  { name: 'F1', code: 'KC_F1', keys: 'f1' },
  { name: 'F2', code: 'KC_F2', keys: 'f2' },
  { name: 'F3', code: 'KC_F3', keys: 'f3' },
  { name: 'F4', code: 'KC_F4', keys: 'f4' },
  { width: 500 },
  { name: 'F5', code: 'KC_F5', keys: 'f5' },
  { name: 'F6', code: 'KC_F6', keys: 'f6' },
  { name: 'F7', code: 'KC_F7', keys: 'f7' },
  { name: 'F8', code: 'KC_F8', keys: 'f8' },
  { width: 500 },
  { name: 'F9', code: 'KC_F9', keys: 'f9' },
  { name: 'F10', code: 'KC_F10', keys: 'f10' },
  { name: 'F11', code: 'KC_F11', keys: 'f11' },
  { name: 'F12', code: 'KC_F12', keys: 'f12' },
  { width: 250 },
  { name: 'Print Screen', code: 'KC_PSCR' },
  { name: 'Scroll Lock', code: 'KC_SLCK' },
  { name: 'Pause', code: 'KC_PAUS' },
  { width: 0 },

  { name: '~\n`', code: 'KC_GRV', keys: '`', hiragana: 'ろ' },
  { name: '!\n1', code: 'KC_1', keys: '1', hiragana: 'ぬ' },
  { name: '@\n2', code: 'KC_2', keys: '2', hiragana: 'ふ' },
  { name: '#\n3', code: 'KC_3', keys: '3', hiragana: 'あ' },
  { name: '$\n4', code: 'KC_4', keys: '4', hiragana: 'う' },
  { name: '%\n5', code: 'KC_5', keys: '5', hiragana: 'え' },
  { name: '^\n6', code: 'KC_6', keys: '6', hiragana: 'お' },
  { name: '&\n7', code: 'KC_7', keys: '7', hiragana: 'や' },
  { name: '*\n8', code: 'KC_8', keys: '8', hiragana: 'ゆ' },
  { name: '(\n9', code: 'KC_9', keys: '9', hiragana: 'よ' },
  { name: ')\n0', code: 'KC_0', keys: '0', hiragana: 'わ' },
  { name: '_\n-', code: 'KC_MINS', keys: '-', hiragana: 'ほ' },
  { name: '+\n=', code: 'KC_EQL', keys: '=', hiragana: 'へ' },
  { name: 'Back Space', code: 'KC_BSPC', keys: 'backspace', width: 2000 },
  { width: 250 },
  { name: 'Insert', code: 'KC_INS', keys: 'insert' },
  { name: 'Home', code: 'KC_HOME', keys: 'home' },
  { name: 'Page Up', code: 'KC_PGUP', keys: 'pageup' },
  { width: 250 },
  { name: 'Num Lock', code: 'KC_NLCK', keys: 'num' },
  { name: '/', code: 'KC_PSLS', keys: 'num_divide' },
  { name: '*', code: 'KC_PAST', keys: 'num_multiply' },
  { name: '-', code: 'KC_PMNS', keys: 'num_subtract' },
  { width: 0 },

  { name: 'Tab', code: 'KC_TAB', keys: 'tab', width: 1500 },
  { name: 'Q', code: 'KC_Q', keys: 'q', hiragana: 'た', hangul: 'ㅂ' },
  { name: 'W', code: 'KC_W', keys: 'w', hiragana: 'て', hangul: 'ㅈ' },
  { name: 'E', code: 'KC_E', keys: 'e', hiragana: 'い', hangul: 'ㄷ' },
  { name: 'R', code: 'KC_R', keys: 'r', hiragana: 'す', hangul: 'ㄱ' },
  { name: 'T', code: 'KC_T', keys: 't', hiragana: 'か', hangul: 'ㅅ' },
  { name: 'Y', code: 'KC_Y', keys: 'y', hiragana: 'ん', hangul: 'ㅛ' },
  { name: 'U', code: 'KC_U', keys: 'u', hiragana: 'な', hangul: 'ㅕ' },
  { name: 'I', code: 'KC_I', keys: 'i', hiragana: 'に', hangul: 'ㅑ' },
  { name: 'O', code: 'KC_O', keys: 'o', hiragana: 'ら', hangul: 'ㅐ' },
  { name: 'P', code: 'KC_P', keys: 'p', hiragana: 'せ', hangul: 'ㅔ' },
  { name: '{\n[', code: 'KC_LBRC', keys: '[', hiragana: '゛' },
  { name: '}\n]', code: 'KC_RBRC', keys: ']', hiragana: '゜' },
  { name: '|\n\\', code: 'KC_BSLS', keys: '\\', hiragana: 'む', width: 1500 },
  { width: 250 },
  { name: 'Del', code: 'KC_DEL', keys: 'delete' },
  { name: 'End', code: 'KC_END', keys: 'end' },
  { name: 'Page Down', code: 'KC_PGDN', keys: 'pagedown' },
  { width: 250 },
  { name: '7', code: 'KC_P7', keys: 'num_7' },
  { name: '8', code: 'KC_P8', keys: 'num_8' },
  { name: '9', code: 'KC_P9', keys: 'num_9' },
  { name: '+', code: 'KC_PPLS', keys: 'num_add' },
  { width: 0 },

  { name: 'Caps Lock', code: 'KC_CAPS', keys: 'caps_lock', width: 1750 },
  { name: 'A', code: 'KC_A', keys: 'a', hiragana: 'ち', hangul: 'ㅁ' },
  { name: 'S', code: 'KC_S', keys: 's', hiragana: 'と', hangul: 'ㄴ' },
  { name: 'D', code: 'KC_D', keys: 'd', hiragana: 'し', hangul: 'ㅇ' },
  { name: 'F', code: 'KC_F', keys: 'f', hiragana: 'は', hangul: 'ㄹ' },
  { name: 'G', code: 'KC_G', keys: 'g', hiragana: 'き', hangul: 'ㅎ' },
  { name: 'H', code: 'KC_H', keys: 'h', hiragana: 'く', hangul: 'ㅗ' },
  { name: 'J', code: 'KC_J', keys: 'j', hiragana: 'ま', hangul: 'ㅓ' },
  { name: 'K', code: 'KC_K', keys: 'k', hiragana: 'の', hangul: 'ㅏ' },
  { name: 'L', code: 'KC_L', keys: 'l', hiragana: 'り', hangul: 'ㅣ' },
  { name: ':\n;', code: 'KC_SCLN', keys: ';', hiragana: 'れ' },
  { name: '"\n\'', code: 'KC_QUOT', keys: "'", hiragana: 'け' },
  { name: 'Enter', code: 'KC_ENT', keys: 'enter', width: 2250 },
  { width: 3500 },
  { name: '4', code: 'KC_P4', keys: 'num_4' },
  { name: '5', code: 'KC_P5', keys: 'num_5' },
  { name: '6', code: 'KC_P6', keys: 'num_6' },
  { name: ',', code: 'KC_PCMM' },
  { width: 0 },

  { name: 'Left Shift', code: 'KC_LSFT', keys: 'shift', width: 2250 },
  { name: 'Z', code: 'KC_Z', keys: 'z', hiragana: 'つ', hangul: 'ㅋ' },
  { name: 'X', code: 'KC_X', keys: 'x', hiragana: 'さ', hangul: 'ㅌ' },
  { name: 'C', code: 'KC_C', keys: 'c', hiragana: 'そ', hangul: 'ㅊ' },
  { name: 'V', code: 'KC_V', keys: 'v', hiragana: 'ひ', hangul: 'ㅍ' },
  { name: 'B', code: 'KC_B', keys: 'b', hiragana: 'こ', hangul: 'ㅠ' },
  { name: 'N', code: 'KC_N', keys: 'n', hiragana: 'み', hangul: 'ㅜ' },
  { name: 'M', code: 'KC_M', keys: 'm', hiragana: 'も', hangul: 'ㅡ' },
  { name: '<\n,', code: 'KC_COMM', keys: ',', hiragana: 'ね' },
  { name: '>\n.', code: 'KC_DOT', keys: '.', hiragana: 'る' },
  { name: '?\n/', code: 'KC_SLSH', keys: '/', hiragana: 'め' },
  { name: 'Right Shift', code: 'KC_RSFT', width: 2750 },
  { width: 1250 },
  { name: 'Up', code: 'KC_UP', keys: 'up' },
  { width: 1250 },
  { name: '1', code: 'KC_P1', keys: 'num_1' },
  { name: '2', code: 'KC_P2', keys: 'num_2' },
  { name: '3', code: 'KC_P3', keys: 'num_3' },
  { name: '=', code: 'KC_PEQL' },
  { width: 0 },

  { name: 'Left Ctrl', code: 'KC_LCTL', keys: 'ctrl', width: 1250 },
  { name: 'Left OS', code: 'KC_LGUI', keys: 'cmd', width: 1250 },
  { name: 'Left Alt', code: 'KC_LALT', keys: 'alt', width: 1250 },
  { name: 'Space', code: 'KC_SPC', keys: 'space', width: 6250 },
  { name: 'Right Alt', code: 'KC_RALT', width: 1250 },
  { name: 'Right OS', code: 'KC_RGUI', width: 1250 },
  { name: 'Menu', code: 'KC_APP', width: 1250 },
  { name: 'Right Ctrl', code: 'KC_RCTL', width: 1250 },
  { width: 250 },
  { name: 'Left', code: 'KC_LEFT', keys: 'left' },
  { name: 'Down', code: 'KC_DOWN', keys: 'down' },
  { name: 'Right', code: 'KC_RGHT', keys: 'right' },
  { width: 250 },
  { name: '0', code: 'KC_P0', keys: 'num_0', width: 2000 },
  { name: '.', code: 'KC_PDOT', keys: 'num_decimal' },
  { name: 'Enter', code: 'KC_PENT', keys: 'num_enter' },

  { label: 'Shifted symbols', width: 'label' },

  { name: '~', code: 'KC_TILD', keys: '~' },
  { name: '!', code: 'KC_EXLM', keys: '!' },
  { name: '@', code: 'KC_AT', keys: '@' },
  { name: '#', code: 'KC_HASH', keys: '#' },
  { name: '$', code: 'KC_DLR', keys: '$' },
  { name: '%', code: 'KC_PERC', keys: '%' },
  { name: '^', code: 'KC_CIRC', keys: '^' },
  { name: '&', code: 'KC_AMPR', keys: '&' },
  { name: '*', code: 'KC_ASTR', keys: '*' },
  { name: '(', code: 'KC_LPRN', keys: '(' },
  { name: ')', code: 'KC_RPRN', keys: ')' },
  { name: '_', code: 'KC_UNDS', keys: '_' },
  { name: '+', code: 'KC_PLUS', keys: '+' },
  { name: '{', code: 'KC_LCBR', keys: '{' },
  { name: '}', code: 'KC_RCBR', keys: '}' },
  { name: '<', code: 'KC_LT', keys: '<' },
  { name: '>', code: 'KC_GT', keys: '>' },
  { name: ':', code: 'KC_COLN', keys: ':' },
  { name: '|', code: 'KC_PIPE', keys: '|' },
  { name: '?', code: 'KC_QUES', keys: '?' },
  { name: '"', code: 'KC_DQUO', keys: '"' }
];
