export default {
  name: 'kat-specimen',
  override: {
    KC_ESC: 'purple-blue',
    KC_F1: 'purple-blue',
    KC_F2: 'purple-blue',
    KC_F3: 'purple-blue',
    KC_F4: 'pink',
    KC_F5: 'orange',
    KC_GRV: 'purple-blue',
    KC_GESC: 'purple-blue',
    KC_1: 'purple-blue',
    KC_2: 'purple-blue',
    KC_3: 'purple-blue',
    KC_4: 'pink',
    KC_5: 'orange',
    KC_TAB: 'purple-blue',
    KC_Q: 'purple-blue',
    KC_W: 'purple-blue',
    KC_CAPS: 'purple-blue',
    KC_A: 'purple-blue',
    KC_LSFT: 'purple-blue',
    KC_NUBS: 'purple-blue',
    KC_LCTL: 'purple-blue',
    KC_E: 'pink',
    KC_R: 'orange',
    KC_S: 'pink',
    KC_D: 'orange',
    KC_Z: 'pink',
    KC_X: 'orange',
    KC_LGUI: 'pink',
    KC_LALT: 'orange',
  }
};
